#!/bin/ksh

# Copyright (c) 2016 Todd T. Fries <todd@fries.net>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

. "${0%/*}/locate-lib"

# 2025-09-22 6e27309 hybrid rsync/rclone + per-dir xz cache and
# date|size|path munge (was single allobsd.xz listing).
apichangedate=1758567522
locate_bootstrap 5 1024 "$apichangedate"
dbname=allobsd.database
cachedir=$HOME/.cache/${me}

cd $datadir || exit 1

while [ "$1" ]
do
	case "$1" in
	-B) build=1;;
	-v) let verbose=verbose+1;;
	*) break;;
	esac
	shift
done

if [ build -eq 0 ]; then
	locate_search_one "$@"
fi

pidfile_acquire
mkdir -p $cachedir

RPATHS=""

addrpath() {
	RPATHS="$1 $RPATHS"
}

# last takes precedence
addrpath "rsync://mirror.esc7.net/openbsd"
addrpath "rsync://ftp.spline.de/OpenBSD"
addrpath "rsync://ftp.hostserver.de/OpenBSD"
addrpath "rsync://ftp.usa.openbsd.org/ftp"
addrpath "rsync://mirror.planetunix.net/OpenBSD/"
addrpath "rsync://mirror.leaseweb.com/openbsd/"

mkdir -p $cachedir

compress() {
	xz -9
}
rsync_lsrmt() {
	rsync --no-motd $RPATH/"$1" | \
	awk '{
		type="/";
		if (substr($1,1,1) == "-") {
			type=""
		};
		if($5 == ".") {
			next
		};
		printf "%s%s\n", $5, type}'
}
rclone_lsrmt() {
	rclone lsd ob-http:"$1" | \
	awk '{
		printf "%s/\n", $5, type}'
}

err="@ERROR: max connections ([0-9]+) reached -- try again later"
for p in $RPATHS
do
	echo "Testing $p"
	if [ "$(rsync --no-motd -l $p/snapshots/amd64/index.txt 2>&1 | egrep "$err")" ]
	then
		continue
	fi
	RPATH="$p"
	break
done

rsync_cache_dir() {
	local d="$1"
	local dname="$(echo "$d"|sed 's,/,_,g')"
	echo "caching rmt dir $d"
	rsync --no-motd -rl --exclude='\.\~tmp\~' $RPATH/${d}/. 2> /dev/null | \
	rsync_mungeforlocate "$d" | \
	compress > ${cachedir}/.${dname}.xz && \
	mv -f ${cachedir}/.${dname}.xz ${cachedir}/${dname}.xz || exit 1
}
rclone_cache_dir() {
	local d="$1"
	local dname="$(echo "$d"|sed 's,/,_,g')"
	echo "caching rmt dir $d"
	rclone lsl ob-http:${d} 2> /dev/null | \
	rclone_mungeforlocate "$d" | \
	compress > ${cachedir}/.${dname}.xz && \
	mv -f ${cachedir}/.${dname}.xz ${cachedir}/${dname}.xz || exit 1
}
	
rclone_mungeforlocate() {
	awk -v d="$1" '
		{
			gsub("-","",$2);
			gsub(":","",$3);
			gsub("\\.[0-9]+","",$3);
			printf "%s%s|%x|%s/%s\n",$2,$3,$1,d,$4;
		}'
}

rsync_mungeforlocate() {
	awk -v d="$1" '
	/\~$/		{next}
	$5 ~ /^\.$/	{next}
	! /^[-d]/	{next}
	/^-/		{t=""}
	/^d/		{t="/"}
			{
				gsub(",","",$2);
				gsub("/","",$3);
				gsub(":","",$4);
				printf "%s%s|%x|%s/%s%s\n",$3,$4,$2,d,$5,t;
			}'
}

# should be static, rm to refresh
for d in $(rclone_lsrmt | egrep "^[0-9].[0-9]/$")
do
	cksys
	d=${d%*/}
	dname="$(echo "$d"|sed 's,/,_,g')"
	if ! [ -f $cachedir/${dname}.xz ]; then
		rclone_cache_dir "$d"
	fi
done

# strip freq dirs off 'all' bits
stripall() {
	awk '/ (ftplist|timestamp|Changelogs|OpenSSH\/portable|patches|snapshots)/{next}{print}'
}

# update each time
for path in {ftplist,timestamp,Changelogs,OpenSSH/portable,patches,snapshots}
do
	cksys
	rsync_cache_dir "$path"
done 

cksys
xzcat $cachedir/*.xz | \
	$sort -u | \
	/usr/libexec/locate.mklocatedb > .$dbname && \
	mv -f .$dbname $dbname
