#!/bin/ksh

# Copyright (c) 2016 Todd T. Fries <todd@fries.net>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

. "${0%/*}/locate-lib"
. "${0%/*}/osmirror-lib"

# 2025-09-22 6e27309 hybrid rsync/rclone + per-dir xz cache and
# date|size|path munge (was single allobsd.xz listing).
apichangedate=1758567522
locate_bootstrap 5 1024 "$apichangedate"
dbname=allobsd.database
cachedir=$HOME/.cache/${me}

# OpenBSD mirror config (thin data for future full driver)
ob_rclone_rmt=${OB_RCLONE_RMT:-ob-http}
ob_rsync_probe=${OB_RSYNC_PROBE:-snapshots/amd64/index.txt}

cd $datadir || exit 1

while [ "$1" ]
do
	case "$1" in
	-B) build=1;;
	-v) let verbose=verbose+1;;
	*) break;;
	esac
	shift
done

if [ build -eq 0 ]; then
	locate_search_one "$@"
fi

pidfile_acquire
mkdir -p $cachedir

# Wrappers preserve historic call shapes (single path arg, fixed remote).
rclone_lsrmt() {
	osmirror_rclone_lsrmt "$ob_rclone_rmt" "$1"
}
rclone_cache_dir() {
	osmirror_rclone_cache_dir "$ob_rclone_rmt" "$1" || exit 1
}
rsync_cache_dir() {
	osmirror_rsync_cache_dir "$1" || exit 1
}
rsync_lsrmt() {
	osmirror_rsync_lsrmt "$1"
}

# last takes precedence (same order as before)
set -- \
	"rsync://mirror.esc7.net/openbsd" \
	"rsync://ftp.spline.de/OpenBSD" \
	"rsync://ftp.hostserver.de/OpenBSD" \
	"rsync://ftp.usa.openbsd.org/ftp" \
	"rsync://mirror.planetunix.net/OpenBSD/" \
	"rsync://mirror.leaseweb.com/openbsd/"
osmirror_pick_rsync_obstyle "$ob_rsync_probe" "$@" || true

# should be static, rm to refresh
for d in $(rclone_lsrmt | egrep "^[0-9].[0-9]/$")
do
	cksys
	d=${d%*/}
	dname=$(osmirror_path_to_dname "$d")
	if ! [ -f $cachedir/${dname}.xz ]; then
		rclone_cache_dir "$d"
	fi
done

# strip freq dirs off 'all' bits (unused; kept for parity with prior script)
stripall() {
	awk '/ (ftplist|timestamp|Changelogs|OpenSSH\/portable|patches|snapshots)/{next}{print}'
}

# update each time
for path in {ftplist,timestamp,Changelogs,OpenSSH/portable,patches,snapshots}
do
	cksys
	rsync_cache_dir "$path"
done

cksys
xzcat $cachedir/*.xz | \
	$sort -u | \
	/usr/libexec/locate.mklocatedb > .$dbname && \
	mv -f .$dbname $dbname
